# AICP Internship Task 1

In [1]:
import numpy as np

## Write a NumPy program to create an array of all even integers from 30 to 70. 

In [2]:
even_integers = np.arange(30,71,2)
even_integers

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

## Write a NumPy program to generate an array of 15 random numbers from a standard normal 
distribution.

In [4]:
random_std = np.random.randn(15)
random_std

array([ 0.1393783 , -0.08632813,  0.49592135, -0.02220229, -0.21363622,
       -0.70955408,  0.09314641, -0.40540383,  0.34625249, -0.07582662,
       -0.34033592,  0.96621444,  0.83692082, -1.56925094, -0.69375619])

In [6]:
random_std.shape

(15,)

In [12]:
random_std.resize(5,3)
random_std

array([[ 0.1393783 , -0.08632813,  0.49592135],
       [-0.02220229, -0.21363622, -0.70955408],
       [ 0.09314641, -0.40540383,  0.34625249],
       [-0.07582662, -0.34033592,  0.96621444],
       [ 0.83692082, -1.56925094, -0.69375619]])

## How to compute the cross-product of two matrices in NumPy?

## A = np.random.randint(