# AICP Internship Task 1

In [1]:
import numpy as np

## Write a NumPy program to create an array of all even integers from 30 to 70. 

In [2]:
even_integers = np.arange(30,71,2)
even_integers

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

## Write a NumPy program to generate an array of 15 random numbers from a standard normal 
distribution.

In [3]:
random_std = np.random.randn(15)
random_std

array([ 0.00307124, -0.89429018,  1.28295311, -1.56593407, -0.97310731,
        0.34676833,  0.53464569, -0.425935  ,  0.03753313, -1.07707205,
        0.8649045 , -1.46886866,  1.25722237, -1.58890554,  0.36062698])

In [4]:
random_std.shape

(15,)

In [5]:
random_std.resize(5,3)
random_std

array([[ 0.00307124, -0.89429018,  1.28295311],
       [-1.56593407, -0.97310731,  0.34676833],
       [ 0.53464569, -0.425935  ,  0.03753313],
       [-1.07707205,  0.8649045 , -1.46886866],
       [ 1.25722237, -1.58890554,  0.36062698]])

## How to compute the cross-product of two matrices in NumPy?

In [9]:
A = np.random.randint(2,15,(2,3))
B = np.random.randint(15,30,(2,2))
np.cross(A,B)

array([[ -92,   80,   87],
       [-144,   96,   48]])

## How to compute the determinant of an array using NumPy?

In [13]:
matrix1 = np.random.randint(1,9,(4,4))
# matrix1
np.linalg.det(matrix1)

1127.9999999999995

## How to create a 3x3x3 array with random values using NumPy?

In [17]:
m = np.random.rand(3,3,3)

In [18]:
m.shape

(3, 3, 3)

## How to create a 5x5 array with random values and find the minimum and maximum values using 
NumPy?

In [26]:
n = np.random.rand(5,5)
n



array([[0.49195869, 0.65699076, 0.37886345, 0.77101682, 0.58725374],
       [0.89540037, 0.86897826, 0.55441887, 0.32847654, 0.13079007],
       [0.91984913, 0.17366651, 0.41734531, 0.61386048, 0.00126243],
       [0.16053648, 0.97781433, 0.05387698, 0.65247084, 0.30952962],
       [0.17989984, 0.15256168, 0.32631499, 0.41067308, 0.85844216]])

In [27]:
n.min()

0.0012624310289214291

In [29]:
n.max()

0.9778143262728082

## How to compute the mean, standard deviation, and variance of a given array along the second axis in 
NumPy?

In [30]:
matrix2 = np.random.randint(1,9,(4,4))
matrix2

array([[3, 2, 7, 6],
       [5, 7, 7, 3],
       [7, 8, 1, 5],
       [7, 4, 5, 4]])

In [34]:
matrix2.mean(axis=1)

array([4.5 , 5.5 , 5.25, 5.  ])

In [35]:
matrix2.std(axis=1)

array([2.06155281, 1.6583124 , 2.68095132, 1.22474487])

In [36]:
matrix2.var(axis=1)

array([4.25  , 2.75  , 7.1875, 1.5   ])